name: iot_dashboard
description: "IoT Dashboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 17.0.1
  # BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # HTTP Client
  dio: ^5.4.0
  # Storage
  shared_preferences: ^2.2.2 
  retrofit: 4.8.0
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.1
  retrofit_generator: 10.1.1
  json_serializable: 6.11.1

flutter:
  uses-material-design: true
